name: shared_clipboard
description: A cross-platform clipboard sharing application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  flutter_webrtc: ^0.9.22
  clipboard_watcher: ^0.2.0
  hotkey_manager: ^0.2.1
  system_tray: ^2.0.2
  window_manager: ^0.3.5
  flutter_background_service: ^2.4.6
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  file_picker: ^5.2.5
  mime: ^1.0.4
  crypto: ^3.0.2
  windows_taskbar: ^1.0.0
  flutter_local_notifications: ^16.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon.ico
